import type { Metadata } from "next";
import { Poppins, Sour_Gummy } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/essential/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

const myFont = Sour_Gummy({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={myFont.className}>
        <Header />
        <div className="body-container">{children}</div>
        <div className="footer"></div>
      </body>
    </html>
  );
}
